# Generated by Django 3.2.6 on 2021-08-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210827_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='trusteeamt',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='trusteemail',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
